# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0011_auto_20170627_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
